import type {
  GuessCandidate,
  GuessQueryValidator,
  GuessRuleValidator,
  WikidataEntity,
} from "@/lib/game"

export type CuratedAnswerEntry = {
  canonicalName: string
  acceptedNames: string[]
  characterName?: string
  notes?: string
}

export type CuratedAnswerLibrary = {
  id: string
  title: string
  sourceLabel: string
  sourceUrl: string
  answerType: "person"
  entries: CuratedAnswerEntry[]
}

function buildPersonEntries(
  names: string[],
  aliases: Record<string, string[]> = {}
): CuratedAnswerEntry[] {
  return names.map((name) => {
    const acceptedNames = new Set([name, ...(aliases[name] ?? [])])
    const asciiName = name.normalize("NFD").replace(/[\u0300-\u036f]/g, "")

    if (asciiName !== name) {
      acceptedNames.add(asciiName)
    }

    return {
      canonicalName: name,
      acceptedNames: [...acceptedNames],
    }
  })
}

export const SILO_SEASON_3_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "silo-season-3-cast",
  title: "Silo Season 3 Cast",
  sourceLabel: "Rotten Tomatoes cast and crew page",
  sourceUrl: "https://www.rottentomatoes.com/tv/silo/s03/cast-and-crew",
  answerType: "person",
  entries: [
    {
      canonicalName: "David Oyelowo",
      acceptedNames: ["David Oyelowo"],
      characterName: "Holston",
    },
    {
      canonicalName: "Rashida Jones",
      acceptedNames: ["Rashida Jones"],
      characterName: "Allison",
    },
    {
      canonicalName: "Rebecca Ferguson",
      acceptedNames: ["Rebecca Ferguson"],
      characterName: "Juliette",
    },
    {
      canonicalName: "Common",
      acceptedNames: ["Common", "Lonnie Rashid Lynn", "Lonnie Rashid Lynn Jr."],
      characterName: "Robert Sims",
      notes: "Common is listed by stage name on Rotten Tomatoes.",
    },
    {
      canonicalName: "Harriet Walter",
      acceptedNames: ["Harriet Walter", "Dame Harriet Walter"],
      characterName: "Martha Walker",
    },
    {
      canonicalName: "Avi Nash",
      acceptedNames: ["Avi Nash"],
      characterName: "Lukas",
    },
    {
      canonicalName: "Rick Gomez",
      acceptedNames: ["Rick Gomez", "Richard Gomez"],
      characterName: "Patrick Kennedy",
    },
    {
      canonicalName: "Chinaza Uche",
      acceptedNames: ["Chinaza Uche"],
      characterName: "Billings",
    },
    {
      canonicalName: "Tim Robbins",
      acceptedNames: ["Tim Robbins", "Timothy Robbins"],
      characterName: "Bernard Holland",
    },
  ],
}

export const ELLE_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "elle-cast",
  title: "Elle Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt32020831/fullcredits/",
  answerType: "person",
  entries: [
    { canonicalName: "Lexi Minetree", acceptedNames: ["Lexi Minetree"] },
    { canonicalName: "June Diane Raphael", acceptedNames: ["June Diane Raphael"] },
    { canonicalName: "Tom Everett Scott", acceptedNames: ["Tom Everett Scott"] },
    { canonicalName: "Jacob Moskovitz", acceptedNames: ["Jacob Moskovitz"] },
    { canonicalName: "Gabrielle Policano", acceptedNames: ["Gabrielle Policano"] },
    { canonicalName: "Chandler Kinney", acceptedNames: ["Chandler Kinney"] },
    { canonicalName: "Zac Looker", acceptedNames: ["Zac Looker"] },
    { canonicalName: "Amy Pietz", acceptedNames: ["Amy Pietz"] },
    { canonicalName: "Jessica Belkin", acceptedNames: ["Jessica Belkin"] },
    { canonicalName: "Filip Fufezan", acceptedNames: ["Filip Fufezan"] },
    { canonicalName: "Danielle Chand", acceptedNames: ["Danielle Chand"] },
    { canonicalName: "Chloe Wepper", acceptedNames: ["Chloe Wepper"] },
    { canonicalName: "Alexander Muir", acceptedNames: ["Alexander Muir"] },
    { canonicalName: "Tamara Kiyama", acceptedNames: ["Tamara Kiyama"] },
    { canonicalName: "Matt Oberg", acceptedNames: ["Matt Oberg"] },
    { canonicalName: "Sophie Thom", acceptedNames: ["Sophie Thom"] },
    { canonicalName: "Sierrah Borjeau", acceptedNames: ["Sierrah Borjeau"] },
    { canonicalName: "James Van Der Beek", acceptedNames: ["James Van Der Beek"] },
    { canonicalName: "Brad Harder", acceptedNames: ["Brad Harder"] },
    { canonicalName: "Taryn Edgar", acceptedNames: ["Taryn Edgar"] },
    { canonicalName: "Anna Katharina", acceptedNames: ["Anna Katharina"] },
    { canonicalName: "David Burtka", acceptedNames: ["David Burtka"] },
    { canonicalName: "Kayla Maisonet", acceptedNames: ["Kayla Maisonet"] },
    { canonicalName: "Logan Shroyer", acceptedNames: ["Logan Shroyer"] },
    { canonicalName: "Sarah Hayward", acceptedNames: ["Sarah Hayward"] },
    { canonicalName: "Luke Humphrey", acceptedNames: ["Luke Humphrey"] },
    { canonicalName: "Lisa Yamada", acceptedNames: ["Lisa Yamada"] },
    { canonicalName: "Kyra Wong", acceptedNames: ["Kyra Wong"] },
    { canonicalName: "Miles Merry", acceptedNames: ["Miles Merry"] },
    { canonicalName: "Brooklyn Hislop", acceptedNames: ["Brooklyn Hislop"] },
    { canonicalName: "Connor Wong", acceptedNames: ["Connor Wong"] },
    { canonicalName: "Sharon Taylor", acceptedNames: ["Sharon Taylor"] },
    { canonicalName: "Teagan Stark", acceptedNames: ["Teagan Stark"] },
    { canonicalName: "Alison Thornton", acceptedNames: ["Alison Thornton"] },
    { canonicalName: "Bonnie Hay", acceptedNames: ["Bonnie Hay"] },
    { canonicalName: "Andrea Abreu", acceptedNames: ["Andrea Abreu"] },
    { canonicalName: "Kristianna Lind", acceptedNames: ["Kristianna Lind"] },
    { canonicalName: "Sean Mathieson", acceptedNames: ["Sean Mathieson"] },
    { canonicalName: "Lea Matina", acceptedNames: ["Lea Matina"] },
    { canonicalName: "Gregory Kendall", acceptedNames: ["Gregory Kendall"] },
    { canonicalName: "Rebecca Wisocky", acceptedNames: ["Rebecca Wisocky"] },
    { canonicalName: "Patrick Fischler", acceptedNames: ["Patrick Fischler"] },
    { canonicalName: "Madeleine Arthur", acceptedNames: ["Madeleine Arthur"] },
    { canonicalName: "Eileen Barrett", acceptedNames: ["Eileen Barrett"] },
    { canonicalName: "Gardiner Millar", acceptedNames: ["Gardiner Millar"] },
    { canonicalName: "Logan Tarasoff", acceptedNames: ["Logan Tarasoff"] },
    { canonicalName: "Daniel Joseph", acceptedNames: ["Daniel Joseph"] },
    { canonicalName: "Kelly-Ruth Mercier", acceptedNames: ["Kelly-Ruth Mercier"] },
    { canonicalName: "Olivia Kate Iatridis", acceptedNames: ["Olivia Kate Iatridis"] },
    { canonicalName: "Courtney Richter", acceptedNames: ["Courtney Richter"] },
    { canonicalName: "Jordana Summer", acceptedNames: ["Jordana Summer"] },
    { canonicalName: "Garrett Quirk", acceptedNames: ["Garrett Quirk"] },
    { canonicalName: "Amy Goodmurphy", acceptedNames: ["Amy Goodmurphy"] },
    { canonicalName: "Nazanin Shoja", acceptedNames: ["Nazanin Shoja"] },
    { canonicalName: "Felix Leblanc", acceptedNames: ["Felix Leblanc"] },
    { canonicalName: "Ash Lee", acceptedNames: ["Ash Lee"] },
    { canonicalName: "Carson Schiefner", acceptedNames: ["Carson Schiefner"] },
    { canonicalName: "Zev Lemke", acceptedNames: ["Zev Lemke"] },
    { canonicalName: "Mackenzie Morrow", acceptedNames: ["Mackenzie Morrow"] },
    { canonicalName: "Erika Bruci", acceptedNames: ["Erika Bruci"] },
    { canonicalName: "Jorden Birch", acceptedNames: ["Jorden Birch"] },
    { canonicalName: "Sigrid Pareja", acceptedNames: ["Sigrid Pareja"] },
    { canonicalName: "Sarah Sheehan", acceptedNames: ["Sarah Sheehan"] },
    { canonicalName: "Janessa St. Pierre", acceptedNames: ["Janessa St. Pierre"] },
    { canonicalName: "Darryl Scheelar", acceptedNames: ["Darryl Scheelar"] },
    { canonicalName: "Micheal Querin", acceptedNames: ["Micheal Querin"] },
    { canonicalName: "Brenna Llewellyn", acceptedNames: ["Brenna Llewellyn"] },
    { canonicalName: "Emily Bandel", acceptedNames: ["Emily Bandel"] },
    { canonicalName: "Bobby Stewart", acceptedNames: ["Bobby Stewart"] },
    { canonicalName: "Halle Gall", acceptedNames: ["Halle Gall"] },
    { canonicalName: "Jericho Cabinas", acceptedNames: ["Jericho Cabinas"] },
    { canonicalName: "Sari Mercer", acceptedNames: ["Sari Mercer"] },
    { canonicalName: "CJ Damaso", acceptedNames: ["CJ Damaso"] },
    { canonicalName: "Nikita Inniss-Boston", acceptedNames: ["Nikita Inniss-Boston"] },
    { canonicalName: "Michael Delleva", acceptedNames: ["Michael Delleva"] },
    { canonicalName: "Ryan Fisher", acceptedNames: ["Ryan Fisher"] },
    { canonicalName: "Megs Calleja", acceptedNames: ["Megs Calleja"] },
    { canonicalName: "Katelyn Vanier", acceptedNames: ["Katelyn Vanier"] },
    { canonicalName: "Cecil MacRae", acceptedNames: ["Cecil MacRae"] },
    { canonicalName: "Adelie Simson", acceptedNames: ["Adelie Simson"] },
    { canonicalName: "Robert Hayley", acceptedNames: ["Robert Hayley"] },
    { canonicalName: "Lynda Steele", acceptedNames: ["Lynda Steele"] },
    { canonicalName: "Grace Chin", acceptedNames: ["Grace Chin"] },
    { canonicalName: "Sebastian Cordoba", acceptedNames: ["Sebastian Cordoba"] },
    {
      canonicalName: "Clazance N'Sungani",
      acceptedNames: ["Clazance N'Sungani", "Clazance N&amp;#x27;Sungani"],
    },
    { canonicalName: "David Stoneham", acceptedNames: ["David Stoneham"] },
    { canonicalName: "Lisa Shields", acceptedNames: ["Lisa Shields"] },
    { canonicalName: "Jacob Tazelaar", acceptedNames: ["Jacob Tazelaar"] },
    { canonicalName: "Matthew Caza", acceptedNames: ["Matthew Caza"] },
    { canonicalName: "Elizabeth Donzis", acceptedNames: ["Elizabeth Donzis"] },
    { canonicalName: "Chris Fassbender", acceptedNames: ["Chris Fassbender"] },
    { canonicalName: "Cecilly Day", acceptedNames: ["Cecilly Day"] },
    { canonicalName: "Ryan MInaKer", acceptedNames: ["Ryan MInaKer"] },
    { canonicalName: "Ava Clarke", acceptedNames: ["Ava Clarke"] },
    { canonicalName: "Virginia Elliot", acceptedNames: ["Virginia Elliot"] },
    { canonicalName: "Taylor Zantingh", acceptedNames: ["Taylor Zantingh"] },
    { canonicalName: "Denys Kravchenko", acceptedNames: ["Denys Kravchenko"] },
    { canonicalName: "Victor Dolhai", acceptedNames: ["Victor Dolhai"] },
    { canonicalName: "Gavin Moya", acceptedNames: ["Gavin Moya"] },
    { canonicalName: "Douglas Chapman", acceptedNames: ["Douglas Chapman"] },
    { canonicalName: "Tyler Paterson", acceptedNames: ["Tyler Paterson"] },
    { canonicalName: "Garreth Roberts", acceptedNames: ["Garreth Roberts"] },
    { canonicalName: "Darryl Quon", acceptedNames: ["Darryl Quon"] },
    { canonicalName: "Maitreyi Ramakrishnan", acceptedNames: ["Maitreyi Ramakrishnan"] },
    { canonicalName: "Gabriel Hogan", acceptedNames: ["Gabriel Hogan"] },
    { canonicalName: "Noah Craig", acceptedNames: ["Noah Craig"] },
    { canonicalName: "Kiara Mcilravey", acceptedNames: ["Kiara Mcilravey"] },
    { canonicalName: "Erin Stoddard", acceptedNames: ["Erin Stoddard"] },
  ],
}

export const THE_TERROR_DEVIL_IN_SILVER_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "the-terror-devil-in-silver-cast",
  title: "The Terror: Devil in Silver Cast",
  sourceLabel: "TMDB cast page",
  sourceUrl:
    "https://www.themoviedb.org/tv/323903-the-terror-devil-in-silver/cast?language=en-US",
  answerType: "person",
  entries: [
    { canonicalName: "Dan Stevens", acceptedNames: ["Dan Stevens"] },
    { canonicalName: "Judith Light", acceptedNames: ["Judith Light"] },
    { canonicalName: "B", acceptedNames: ["B", "b"] },
    { canonicalName: "Hampton Fluker", acceptedNames: ["Hampton Fluker"] },
    { canonicalName: "CCH Pounder", acceptedNames: ["CCH Pounder"] },
    {
      canonicalName: "Mel Johnson Jr.",
      acceptedNames: ["Mel Johnson Jr.", "Mel Johnson Jr"],
    },
    {
      canonicalName: "Celia Keenan-Bolger",
      acceptedNames: ["Celia Keenan-Bolger", "Celia Keenan Bolger"],
    },
    { canonicalName: "Larry Marshall", acceptedNames: ["Larry Marshall"] },
    { canonicalName: "Maureen Sebastian", acceptedNames: ["Maureen Sebastian"] },
    { canonicalName: "Andrea Syglowski", acceptedNames: ["Andrea Syglowski"] },
    {
      canonicalName: "John Benjamin Hickey",
      acceptedNames: ["John Benjamin Hickey"],
    },
    { canonicalName: "Aasif Mandvi", acceptedNames: ["Aasif Mandvi"] },
    { canonicalName: "Chinaza Uche", acceptedNames: ["Chinaza Uche"] },
    { canonicalName: "Michael Aronov", acceptedNames: ["Michael Aronov"] },
    { canonicalName: "Marin Ireland", acceptedNames: ["Marin Ireland"] },
    { canonicalName: "Stephen Root", acceptedNames: ["Stephen Root"] },
    { canonicalName: "Juani Feliz", acceptedNames: ["Juani Feliz"] },
    { canonicalName: "Hayward Leach", acceptedNames: ["Hayward Leach"] },
    { canonicalName: "Siddiq Saunderson", acceptedNames: ["Siddiq Saunderson"] },
    { canonicalName: "Philip Ettinger", acceptedNames: ["Philip Ettinger"] },
    { canonicalName: "Manuel Herrera", acceptedNames: ["Manuel Herrera"] },
    { canonicalName: "Teagan Meredith", acceptedNames: ["Teagan Meredith"] },
    { canonicalName: "Susanna Guzman", acceptedNames: ["Susanna Guzman"] },
    { canonicalName: "Jason Babinsky", acceptedNames: ["Jason Babinsky"] },
    { canonicalName: "Joseph Baucum", acceptedNames: ["Joseph Baucum"] },
    { canonicalName: "Kennedy McMann", acceptedNames: ["Kennedy McMann"] },
    {
      canonicalName: "Stephen C. Bradbury",
      acceptedNames: ["Stephen C. Bradbury", "Stephen C Bradbury"],
    },
    { canonicalName: "Christopher Rhodes", acceptedNames: ["Christopher Rhodes"] },
    {
      canonicalName: "Sean Patrick Folster",
      acceptedNames: ["Sean Patrick Folster"],
    },
    { canonicalName: "Ali Skamangas", acceptedNames: ["Ali Skamangas"] },
    {
      canonicalName: "Luis Rivera Figueroa",
      acceptedNames: ["Luis Rivera Figueroa"],
    },
    {
      canonicalName: "Maboud Ebrahimzadeh",
      acceptedNames: ["Maboud Ebrahimzadeh"],
    },
    { canonicalName: "Joel Newsome", acceptedNames: ["Joel Newsome"] },
    { canonicalName: "Celia Schaefer", acceptedNames: ["Celia Schaefer"] },
    { canonicalName: "Brittany Bradford", acceptedNames: ["Brittany Bradford"] },
    { canonicalName: "Eli Gelb", acceptedNames: ["Eli Gelb"] },
    {
      canonicalName: "Robert Sean Leonard",
      acceptedNames: ["Robert Sean Leonard"],
    },
    { canonicalName: "Pavel Shatu", acceptedNames: ["Pavel Shatu"] },
    { canonicalName: "Andrew Polk", acceptedNames: ["Andrew Polk"] },
    { canonicalName: "Carlos Lopez", acceptedNames: ["Carlos Lopez"] },
    {
      canonicalName: "Emma Pfitzer Price",
      acceptedNames: ["Emma Pfitzer Price"],
    },
    {
      canonicalName: "Christopher M. Ramirez",
      acceptedNames: ["Christopher M. Ramirez", "Christopher M Ramirez"],
    },
  ],
}

export const WORST_NEIGHBOR_EVER_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "worst-neighbor-ever-cast",
  title: "Worst Neighbor Ever Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt43476716/fullcredits/",
  answerType: "person",
  entries: [
    { canonicalName: "Caroline Herrling", acceptedNames: ["Caroline Herrling"] },
    { canonicalName: "Charles Wilding", acceptedNames: ["Charles Wilding"] },
    { canonicalName: "Bella Baskin", acceptedNames: ["Bella Baskin"] },
    { canonicalName: "Ashley Lee", acceptedNames: ["Ashley Lee"] },
    { canonicalName: "Frances Zaayer", acceptedNames: ["Frances Zaayer"] },
    { canonicalName: "Melina Armstead", acceptedNames: ["Melina Armstead"] },
    { canonicalName: "Shawna Scott", acceptedNames: ["Shawna Scott"] },
    { canonicalName: "Miles Armstead", acceptedNames: ["Miles Armstead"] },
    { canonicalName: "Lyndon Versoza", acceptedNames: ["Lyndon Versoza"] },
    { canonicalName: "Haley Boyd", acceptedNames: ["Haley Boyd"] },
    { canonicalName: "David Scott", acceptedNames: ["David Scott"] },
    { canonicalName: "Abby Jackson", acceptedNames: ["Abby Jackson"] },
    { canonicalName: "Lance Lockridge", acceptedNames: ["Lance Lockridge"] },
    { canonicalName: "Jason Kroth", acceptedNames: ["Jason Kroth"] },
    { canonicalName: "Mark Ray Leonard", acceptedNames: ["Mark Ray Leonard"] },
    { canonicalName: "Mark O'Donnell", acceptedNames: ["Mark O'Donnell"] },
    { canonicalName: "Gloria Olvey", acceptedNames: ["Gloria Olvey"] },
    { canonicalName: "Bonnie Bailer", acceptedNames: ["Bonnie Bailer"] },
    { canonicalName: "Wanda Collinsworth", acceptedNames: ["Wanda Collinsworth"] },
    { canonicalName: "Kyle Boyd", acceptedNames: ["Kyle Boyd"] },
    { canonicalName: "Mark Hollingsworth", acceptedNames: ["Mark Hollingsworth"] },
    {
      canonicalName: "Mionserrate Shirley",
      acceptedNames: ["Mionserrate Shirley"],
    },
    { canonicalName: "Andrew Brown", acceptedNames: ["Andrew Brown"] },
    { canonicalName: "Kat Olvey", acceptedNames: ["Kat Olvey"] },
    { canonicalName: "Doug Aldridge", acceptedNames: ["Doug Aldridge"] },
    { canonicalName: "Michael Eggleston", acceptedNames: ["Michael Eggleston"] },
    { canonicalName: "Faith Lewis", acceptedNames: ["Faith Lewis"] },
    { canonicalName: "Jamal Thomas", acceptedNames: ["Jamal Thomas"] },
    { canonicalName: "Matt Guido", acceptedNames: ["Matt Guido"] },
    { canonicalName: "Duane Kidd", acceptedNames: ["Duane Kidd"] },
    { canonicalName: "Adante Pointer", acceptedNames: ["Adante Pointer"] },
    {
      canonicalName: "Jennifer Longworth",
      acceptedNames: ["Jennifer Longworth"],
    },
    { canonicalName: "Terell Bostic", acceptedNames: ["Terell Bostic"] },
    { canonicalName: "Owen Boyd", acceptedNames: ["Owen Boyd"] },
    { canonicalName: "Andrew Reinhardt", acceptedNames: ["Andrew Reinhardt"] },
    { canonicalName: "Rafael Sanchez", acceptedNames: ["Rafael Sanchez"] },
    { canonicalName: "Dion Longworth", acceptedNames: ["Dion Longworth"] },
    { canonicalName: "Tylor Smith", acceptedNames: ["Tylor Smith"] },
    { canonicalName: "John Longworth", acceptedNames: ["John Longworth"] },
    { canonicalName: "Robert Leonard", acceptedNames: ["Robert Leonard"] },
    { canonicalName: "Toni Bostic", acceptedNames: ["Toni Bostic"] },
    { canonicalName: "Jose Sanchez", acceptedNames: ["Jose Sanchez"] },
    { canonicalName: "Emily Voss", acceptedNames: ["Emily Voss"] },
    { canonicalName: "Butch Ford", acceptedNames: ["Butch Ford"] },
  ],
}

export const ENOLA_HOLMES_3_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "enola-holmes-3-cast",
  title: "Enola Holmes 3 Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt32278481/fullcredits/",
  answerType: "person",
  entries: [
    { canonicalName: "Millie Bobby Brown", acceptedNames: ["Millie Bobby Brown"] },
    { canonicalName: "Henry Cavill", acceptedNames: ["Henry Cavill"] },
    {
      canonicalName: "Helena Bonham Carter",
      acceptedNames: ["Helena Bonham Carter"],
    },
    { canonicalName: "Louis Partridge", acceptedNames: ["Louis Partridge"] },
    { canonicalName: "Himesh Patel", acceptedNames: ["Himesh Patel"] },
    {
      canonicalName: "Sharon Duncan-Brewster",
      acceptedNames: ["Sharon Duncan-Brewster"],
    },
    { canonicalName: "Hattie Morahan", acceptedNames: ["Hattie Morahan"] },
    { canonicalName: "Susan Wokoma", acceptedNames: ["Susan Wokoma"] },
    { canonicalName: "Joe Azzopardi", acceptedNames: ["Joe Azzopardi"] },
    { canonicalName: "Nicholas Aaron", acceptedNames: ["Nicholas Aaron"] },
    { canonicalName: "Michela Farrugia", acceptedNames: ["Michela Farrugia"] },
    { canonicalName: "David Sterne", acceptedNames: ["David Sterne"] },
    { canonicalName: "Jason Watkins", acceptedNames: ["Jason Watkins"] },
    { canonicalName: "Paul Cawley", acceptedNames: ["Paul Cawley"] },
    { canonicalName: "Myron Ellul", acceptedNames: ["Myron Ellul"] },
    { canonicalName: "Robbie O'Neill", acceptedNames: ["Robbie O'Neill"] },
    { canonicalName: "Stephen Chance", acceptedNames: ["Stephen Chance"] },
    {
      canonicalName: "Nichollette Yardley-Moore",
      acceptedNames: ["Nichollette Yardley-Moore"],
    },
    { canonicalName: "Rodrig Andrisan", acceptedNames: ["Rodrig Andrisan"] },
    { canonicalName: "Bern Collaço", acceptedNames: ["Bern Collaço", "Bern Collaco"] },
    { canonicalName: "Nick Davison", acceptedNames: ["Nick Davison"] },
    { canonicalName: "Maxime Durand", acceptedNames: ["Maxime Durand"] },
    { canonicalName: "Alex Gasperetti", acceptedNames: ["Alex Gasperetti"] },
    { canonicalName: "Liam Jeffrey", acceptedNames: ["Liam Jeffrey"] },
    { canonicalName: "Kurt Laferla", acceptedNames: ["Kurt Laferla"] },
    { canonicalName: "Mike Parish", acceptedNames: ["Mike Parish"] },
    { canonicalName: "Tyler Valerie", acceptedNames: ["Tyler Valerie"] },
    { canonicalName: "Peter Winfield", acceptedNames: ["Peter Winfield"] },
    { canonicalName: "James Wright", acceptedNames: ["James Wright"] },
    { canonicalName: "Theodore Zammit", acceptedNames: ["Theodore Zammit"] },
  ],
}

export const RENOVATION_RESORT_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "renovation-resort-cast",
  title: "Renovation Resort Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt26442970/fullcredits/",
  answerType: "person",
  entries: [
    { canonicalName: "Scott McGillivray", acceptedNames: ["Scott McGillivray"] },
    { canonicalName: "Bryan Baeumler", acceptedNames: ["Bryan Baeumler"] },
    { canonicalName: "Rasheeda Gray", acceptedNames: ["Rasheeda Gray"] },
    { canonicalName: "Jake Gray", acceptedNames: ["Jake Gray"] },
    { canonicalName: "Melissa Herriott", acceptedNames: ["Melissa Herriott"] },
    { canonicalName: "Shannon Evans", acceptedNames: ["Shannon Evans"] },
    { canonicalName: "Camille Normandin", acceptedNames: ["Camille Normandin"] },
    { canonicalName: "Chris McGimsie", acceptedNames: ["Chris McGimsie"] },
    { canonicalName: "Hollie Laird", acceptedNames: ["Hollie Laird"] },
    { canonicalName: "Rotem Lamsee", acceptedNames: ["Rotem Lamsee"] },
    { canonicalName: "Graham Laird", acceptedNames: ["Graham Laird"] },
    { canonicalName: "Troy Lamsee", acceptedNames: ["Troy Lamsee"] },
    { canonicalName: "April Gandy", acceptedNames: ["April Gandy"] },
    { canonicalName: "Arnold Tate", acceptedNames: ["Arnold Tate"] },
    { canonicalName: "Jena Nasser", acceptedNames: ["Jena Nasser"] },
    { canonicalName: "Sean Henshall", acceptedNames: ["Sean Henshall"] },
    { canonicalName: "Savannah Kokaliares", acceptedNames: ["Savannah Kokaliares"] },
    { canonicalName: "Kyle Kokaliares", acceptedNames: ["Kyle Kokaliares"] },
    { canonicalName: "Debra Salmoni", acceptedNames: ["Debra Salmoni"] },
    { canonicalName: "Sarah Keenleyside", acceptedNames: ["Sarah Keenleyside"] },
    { canonicalName: "Sarah Baeumler", acceptedNames: ["Sarah Baeumler"] },
    { canonicalName: "Sabrina McGillivray", acceptedNames: ["Sabrina McGillivray"] },
    {
      canonicalName: "Tatianna Taylor-Tait",
      acceptedNames: ["Tatianna Taylor-Tait"],
    },
    { canonicalName: "Thomas Markley", acceptedNames: ["Thomas Markley"] },
    { canonicalName: "Marcy Mussari", acceptedNames: ["Marcy Mussari"] },
    { canonicalName: "Melissa Mussari", acceptedNames: ["Melissa Mussari"] },
    { canonicalName: "Chalon Clark", acceptedNames: ["Chalon Clark"] },
    { canonicalName: "Liz Truluck", acceptedNames: ["Liz Truluck"] },
    { canonicalName: "Taylor Reiko", acceptedNames: ["Taylor Reiko"] },
    { canonicalName: "Mehrdad Amini", acceptedNames: ["Mehrdad Amini"] },
    { canonicalName: "Christine Tizzard", acceptedNames: ["Christine Tizzard"] },
    { canonicalName: "Natalie Preddie", acceptedNames: ["Natalie Preddie"] },
    { canonicalName: "Carson Arthur", acceptedNames: ["Carson Arthur"] },
    {
      canonicalName: "Heather Greenwood Davis",
      acceptedNames: ["Heather Greenwood Davis"],
    },
    { canonicalName: "Mactar Mbaye", acceptedNames: ["Mactar Mbaye"] },
    { canonicalName: "Ali Budd", acceptedNames: ["Ali Budd"] },
    { canonicalName: "Caffery Vanhorne", acceptedNames: ["Caffery Vanhorne"] },
    { canonicalName: "Charlie Preddie", acceptedNames: ["Charlie Preddie"] },
  ],
}

export const SILO_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "silo-cast",
  title: "Silo Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt14688458/fullcredits/",
  answerType: "person",
  entries: buildPersonEntries([
    "Rebecca Ferguson",
    "Common",
    "Chinaza Uche",
    "Harriet Walter",
    "Tim Robbins",
    "Avi Nash",
    "Remmie Milner",
    "Shane McRae",
    "Rick Gomez",
    "Billy Postlethwaite",
    "Caitlin Zoz",
    "Alexandria Riley",
    "Iain Glen",
    "Chipo Chung",
    "Olatunji Ayofe",
    "Angela Yeoh",
    "Carlos Damasceno",
    "Michael Blight",
    "Steve Zahn",
    "Akie Kotabe",
    "Clare Perkins",
    "Ashley Zukerman",
    "Christian Ochoa Lavernia",
    "Tanya Moodie",
    "Jessica Henwick",
    "Liam Akpan",
    "Matt Gomez Hidaka",
    "David Oyelowo",
    "Ferdinand Kingsley",
    "Taj Kandula",
    "Khairika Sinani",
    "Oscar Coleman",
    "Sonita Henry",
    "Daniel Eghan",
    "Will Patton",
    "Amelie Child Villiers",
    "Will Merrick",
    "Helene Maksoud",
    "Jacqueline Berces",
    "Florian Clare",
    "Geraldine James",
    "Sophie Thompson",
    "Henry Garrett",
    "Matt Craven",
    "Peter Gadiot",
    "George Robinson",
    "Georgie Sadler",
    "Nick Haverson",
    "Orlando Norman",
    "Sara Hazemi",
    "Fahad Shaft",
    "Ross McCall",
    "Sienna Guillory",
    "Ida Brooke",
    "Reed Birney",
    "Morven Christie",
    "Jessica Brown Findlay",
    "Brendan Howley",
    "Uche Abuah",
    "Lolita Chakrabarti",
    "Sacharissa Claxton",
    "Reggie Absolom",
    "Maria Teresa Creasey",
    "Kaja Chan",
    "LaToya Harding",
    "Ema Kosac",
    "Ricky Shah",
    "Georgina Arthur",
    "Cameron Bell",
    "Greg Hemphill",
    "Harriet Barrow",
    "Lia Goresh",
    "Rashida Jones",
    "Peter Parker Mensah",
    "Finn Guegan",
    "Laura Innes",
    "Brian Bovell",
    "Andrew P Stephen",
    "Pippa Winslow",
    "Roderick Hill",
    "Aleah Aberdeen",
    "Simon Armstrong",
    "Damian Schedler Cruz",
    "Lee Drage",
    "Joshua Merara",
    "Jasmine Imboden",
    "Kosha Engler",
    "Delroy Atkinson",
    "Carryl Thomas",
    "Charlie Coombes",
    "Ayaaz Tariq",
    "Kieron Jecchinis",
    "Nari Blair-Mangat",
    "Georgia Goodman",
    "Nimisha Odedra",
    "Cole Vernon",
    "Michael Magnet",
    "Kumbi Mushambi",
    "Isabelle Schuler",
    "Elizabeth Bagnall",
    "Caitlin Innes Edwards",
    "Robyn Lovell",
    "Ned Dennehy",
    "Alana Maria",
    "Paul Bigley",
    "Paul Herzberg",
    "Michael-Alan Read",
    "Bill Bagnall",
    "Stefan Trout",
    "Gabeen Khan",
    "Chris Fulton",
    "James Palmer",
    "Bruce Lester Johnson",
    "Nick Judge",
    "Jarren Dalmeda",
    "Alice Bounsall",
    "Brandon Marinas",
    "James Day",
    "Rowan Vickers",
    "Shannon Taiwo",
    "Rose De Vera",
    "Frances Gilbert",
    "Krishan Naidoo",
    "Nathan Clough",
    "James Payton",
    "Ojan Genc",
    "Mark Ramsay",
    "James McGregor",
    "Téa Chung",
    "Zheng Xi Yong",
    "Mickey Mason",
    "Jon Chew",
    "Ankur Bahl",
    "Chris Anderson",
    "Andy Linden",
    "Sarah Farrell",
    "Levi Goldmeier",
    "Ross Armstrong",
    "Noelle Adames",
    "Díana Bermudez",
    "Indigo Griffiths",
    "Tom Cox",
    "Stuart Milligan",
    "Quelin Sepulveda",
    "Anna Siow",
    "David Bromley",
    "Kevin Badu",
    "Celine Arden",
    "Marcello Cruz",
    "Jay Rincon",
    "Brian Law",
    "Teddy Linard",
    "Larry Olubamiwo",
    "Samantha Jonczyk",
    "Tuwaine Barrett",
    "Stacy Liu",
    "Imogen Butler-Cole",
    "Micah Abna",
    "Donna Louise Bryan",
    "Michael Younis",
    "Matt Addis",
    "Stephen Aaron-Sipple",
    "Stephen Leask",
    "Max Mindell",
    "Matthew Charlery-Smith",
    "Alfredo Tavares",
    "Joseph Balderrama",
    "Adonis Kapsalis",
    "Manoj Anand",
    "Robert Ryan",
    "Celina Nessa",
    "Daniel Osgood",
    "Rita McDonald Damper",
    "Cain Aiden",
    "Ketan Majmudar",
    "A.k. Steppa",
    "Ana Zab",
    "Pierre Bergman",
    "Ruth Clarson",
    "Yash Agnihotri",
    "Bharat Mistri",
    "Darryl Bradford",
    "Morteza Khodabakhsh",
    "Jessie Vinning",
    "Atul Sharma",
    "Jo Wheatley",
    "Babita Christie",
    "Haroon Rafiq",
    "Adams-Junior Dauda",
    "Mariia Legun",
    "Diya Jandu",
    "Wendy-Anne Daloz",
    "Gino Picciano",
    "Tina Tancak",
    "Omar Alboukharey",
    "Chi Chan",
    "Sachiko Yokoyama",
    "Elizabeth Ansari",
    "John McHale",
    "Alex Madden",
    "Patrick Loh",
    "Carl Spiegel",
    "Jayne Michele Pacitto",
    "Cedar Rose Johnson",
    "Asha Patel",
    "Jai Patel",
    "Bobby Bedi",
    "Sharan Hunjan",
    "Poppy Townsend White",
    "Claire Ashton",
    "Stephen Samson",
    "Nick Davison",
    "Kenny-Lee Mbanefo",
    "Christopher Moore",
    "Dipali Limbachia",
    "Sharif Islam",
    "Israr Azam",
    "Ty Hopkins",
    "Sanj Surati",
    "Anil Christie",
    "Richard Sutar",
    "Tabitha Green",
    "Lee Goode",
    "Stephen Hulse",
    "Paul Fairlie",
    "Kevin Hamlet",
    "Van Pierre",
    "Charles Timson",
    "Imre Elekes",
    "Brian Rodger",
    "Dave Watts",
    "Osa Edeki",
    "Sylvana Savvas",
    "Rosie Hancock",
    "Andy M Milligan",
    "Jason Thomas Brown",
    "Leo Samson Dahno",
    "Amore Psiche",
    "Lula Carr",
    "Deone Jackson",
    "Abid Mohammed",
    "Maria Nekisheva",
    "Joshua L Franklin",
    "Rafael Piamolini",
    "Tiffany Gray",
    "Oliver Branson-Cole",
    "Anita Moore",
    "Nirmal Fernando",
  ]),
}

export const LITTLE_HOUSE_ON_THE_PRAIRIE_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "little-house-on-the-prairie-cast",
  title: "Little House on the Prairie Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt2431250/fullcredits/",
  answerType: "person",
  entries: buildPersonEntries([
    "Luke Bracey",
    "Crosby Fitzgerald",
    "Alice Halsey",
    "Skywalker Hughes",
    "Kowen Cadorath",
    "Jocko Sims",
    "Barrett Doss",
    "Mary Holland",
    "Warren Christie",
    "Meegwun Fairbrother",
    "Alyssa Wapanatâhk",
    "Wren Zhawenim Gotts",
    "Maclean Fish",
    "Rebecca Amzallag",
    "Michael Hough",
    "Ryan Robbins",
    "Xander Cole",
    "Sharon Bajer",
    "Lexie Cypurda",
    "Connor Paton",
    "Catherine Bérubé",
    "Daylin Willis",
    "Thosh Collins",
    "Zoe Fish",
    "Cliff Sumter",
    "Paisley Cadorath",
    "Corvin Mack",
    "Daniel Falk",
    "Paul Andrich",
    "Alison Arngrim",
    "Martin Donovan",
    "Aaron Merke",
    "Andrea Greening",
    "Talee Redcorn",
    "Tyler Baigrie",
    "Ryan David Younes",
    "Laura Lieben",
    "Tom Young",
    "Matthew Bennett",
    "Willa Dunn",
    "Megan Follows",
  ]),
}

export const THE_FIVE_STAR_WEEKEND_CAST_LIBRARY: CuratedAnswerLibrary = {
  id: "the-five-star-weekend-cast",
  title: "The Five-Star Weekend Cast",
  sourceLabel: "IMDb full cast and crew page",
  sourceUrl: "https://www.imdb.com/title/tt35587659/fullcredits/",
  answerType: "person",
  entries: buildPersonEntries([
    "Jennifer Garner",
    "Regina Hall",
    "D'Arcy Carden",
    "Chloë Sevigny",
    "Harlow Jane",
    "Gemma Chan",
    "Henry Eikenberry",
    "Vella Lovell",
    "Roberta Colindrez",
    "Morrison Keddie",
    "Chuck McCollum",
    "Timothy Olyphant",
    "Josh Hamilton",
    "David Denman",
    "West Duchovny",
    "Rob Huebel",
    "Judy Greer",
    "P.J. Byrne",
    "Jenna Bush Hager",
    "Zoe Renee",
    "Tory Devon Smith",
    "Jonathan Trevone Moore",
    "Lisagaye Tomlinson",
    "Richie Maynes",
    "Sarah Cortez",
    "Paige Hullett",
    "Megan Barlow",
    "Wes Martinez",
    "Patrick Quinlan",
    "Nicole Leanne Nelson",
    "Jess Nurse",
    "Jaimie Paulson",
    "Alexia Dox",
    "Kelsie Kiana Piini",
    "Micah Giovanni",
    "Lauren Mendoza",
    "Henry Noble",
    "Sienna Ribeiro",
    "Preston James Hillier",
    "Saphirah Kiss",
  ]),
}

export const CURATED_ANSWER_LIBRARIES: Record<string, CuratedAnswerLibrary> = {
  [SILO_SEASON_3_CAST_LIBRARY.id]: SILO_SEASON_3_CAST_LIBRARY,
  [ELLE_CAST_LIBRARY.id]: ELLE_CAST_LIBRARY,
  [THE_TERROR_DEVIL_IN_SILVER_CAST_LIBRARY.id]:
    THE_TERROR_DEVIL_IN_SILVER_CAST_LIBRARY,
  [WORST_NEIGHBOR_EVER_CAST_LIBRARY.id]: WORST_NEIGHBOR_EVER_CAST_LIBRARY,
  [ENOLA_HOLMES_3_CAST_LIBRARY.id]: ENOLA_HOLMES_3_CAST_LIBRARY,
  [RENOVATION_RESORT_CAST_LIBRARY.id]: RENOVATION_RESORT_CAST_LIBRARY,
  [SILO_CAST_LIBRARY.id]: SILO_CAST_LIBRARY,
  [LITTLE_HOUSE_ON_THE_PRAIRIE_CAST_LIBRARY.id]:
    LITTLE_HOUSE_ON_THE_PRAIRIE_CAST_LIBRARY,
  [THE_FIVE_STAR_WEEKEND_CAST_LIBRARY.id]: THE_FIVE_STAR_WEEKEND_CAST_LIBRARY,
}

function normalizeAnswerName(value: string) {
  return value
    .toLowerCase()
    .replace(/[.'’]/g, "")
    .replace(/\s+/g, " ")
    .trim()
}

function buildCuratedQid(libraryId: string, index: number) {
  const prefix =
    libraryId
      .split("-")
      .map((segment) => segment.replace(/[^a-z0-9]/gi, ""))
      .filter(Boolean)
      .map((segment) => segment.match(/^\d+$/) ? segment : segment[0])
      .join("")
      .toLowerCase() || "cur"

  return `cur:${prefix}:${index + 1}`
}

function getEntityCandidateNames(entity: WikidataEntity | null) {
  if (!entity) {
    return []
  }

  const names = new Set<string>()

  for (const label of Object.values(entity.labels ?? {})) {
    if (label?.value) {
      names.add(normalizeAnswerName(label.value))
    }
  }

  return [...names]
}

export function buildCuratedPersonValidator(
  library: CuratedAnswerLibrary
): GuessRuleValidator {
  const acceptedEntries = library.entries.map((entry) => ({
    ...entry,
    normalizedAcceptedNames: entry.acceptedNames.map(normalizeAnswerName),
  }))

  return (entity: WikidataEntity | null): GuessCandidate => {
    if (!entity) {
      return {
        valid: false,
        qid: "",
        name: "",
      }
    }

    const candidateNames = getEntityCandidateNames(entity)
    const match = acceptedEntries.find((entry) =>
      entry.normalizedAcceptedNames.some((acceptedName) =>
        candidateNames.includes(acceptedName)
      )
    )

    return {
      valid: Boolean(match),
      qid: entity.id,
      name: match?.canonicalName ?? entity.labels?.en?.value ?? entity.id,
    }
  }
}

export function buildCuratedPersonQueryValidator(
  library: CuratedAnswerLibrary
): GuessQueryValidator {
  const acceptedEntries = library.entries.map((entry, index) => ({
    ...entry,
    normalizedAcceptedNames: entry.acceptedNames.map(normalizeAnswerName),
    qid: buildCuratedQid(library.id, index),
  }))

  return (query: string): GuessCandidate => {
    const normalizedQuery = normalizeAnswerName(query)
    const match = acceptedEntries.find((entry) =>
      entry.normalizedAcceptedNames.includes(normalizedQuery)
    )

    return {
      valid: Boolean(match),
      qid: match?.qid ?? "",
      name: match?.canonicalName ?? query.trim(),
    }
  }
}
